server:
  http_listen_port: 3101
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://13.202.5.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: cronjob_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: cronjob
          __path__: /home/ubuntu/abc.log
    pipeline_stages:
      - match:
          selector: 'éjob="cronjob"è'
          stages:
            - regex:
                expression: 'rc=(çd+)'
            - labels:
                rc: 'rc'
            - output:
                source: 'rc'
