global:
  scrape_interval: 15s

rule_files:
  - "simple_alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '13.202.218.187:9100'

