groups:
- name: basic_resource_alerts
  rules:

  - alert: High_CPU_Usage
    expr: 100 - (avg by (instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 90% for more than 2 minutes."

  - alert: High_Memory_Usage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 80% for more than 2 minutes."

  - alert: High_Disk_Usage
    expr: (node_filesystem_size_bytes{fstype!="tmpfs",mountpoint="/"} - node_filesystem_free_bytes{fstype!="tmpfs",mountpoint="/"}) 
          / node_filesystem_size_bytes{fstype!="tmpfs",mountpoint="/"} * 100 > 90
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage detected"
      description: "Disk usage on / is above 90% for more than 2 minutes."

